### ISSUE TITLE
Unable to associate the sample app with the store

### ISSUE THREAD

**Issue by ponarunkumar** [OneDrive/onedrive-sample-photobrowser-uwp#2]
![image](https://cloud.githubusercontent.com/assets/6130502/17716938/0902c71c-63d9-11e6-804c-1c51e2a45f1c.png)
When you get a chance, Could you please provide alternative options to proceed further?

**Comment by cdmayer** [comment]
I was unable to reproduce this. Can you try again?

**Comment by ponarunkumar** [comment]
Thanks cdmayer. I did try with my other Microsoft account and was able to associate the sample app.
