### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-sample-photobrowser-uwp#7]
AccountSelection.xaml.cs(125,52,125,82): error CS0246: The type or namespace name 'OnlineIdAuthenticationProvider' could not be found

**Comment by hermitdave** [comment]
I encountered the same issue.

**Comment by cdmayer** [comment]
Have you upgraded to the newest version of the OneDrive.Sdk.Authentication package? That type is only available in newer versions.

**Comment by hermitdave** [comment]
This is just pulling whatever you had in project.json. I just commented it out and using the non uwp one

**Comment by cdmayer** [comment]
Thank you for reporting! Fixed.
